### ISSUE TITLE
(1) Dunning List View Changes

### ISSUE THREAD

**Issue by dottenbr** [newmatik/dunning#26]
![image](https://user-images.githubusercontent.com/9136094/70432236-12fd9980-1a7f-11ea-8780-e6c6691556b1.png)

**Comment by KanchanChauhan** [comment]
@dottenbr Cannot remove name since that is the link field to the document and it is by default. Only way to remove this by having title setup (add new field title, automatically set it to customer name and have a link to the document), then the title will show instead of the name.

<img width="981" alt="Screen Shot 2019-12-09 at 6 00 12 PM" src="https://user-images.githubusercontent.com/16913064/70437590-f0d13f00-1ab1-11ea-957a-2159f4ffc58e.png">

**Comment by dottenbr** [comment]
Just set the customer name as title and then the PR-DE ... is on the right

**Comment by KanchanChauhan** [comment]
@dottenbr Done
<img width="1173" alt="Screen Shot 2019-12-09 at 7 44 06 PM" src="https://user-images.githubusercontent.com/16913064/70442526-896cbc80-1abc-11ea-9bbd-e4cdce404db8.png">

**Comment by creamdory** [comment]
@KanchanChauhan wrong value for `Customer` Name in Prod for Dunning.

![Dunning 2019-12-10 15-12-09](https://user-images.githubusercontent.com/21003054/70503980-a3131000-1b5f-11ea-9c6d-a57aa214ff92.png)

**Comment by KanchanChauhan** [comment]
@creamdory We need a patch for Prod. Writing it now.

**Comment by creamdory** [comment]
### STAGING TEST PASS

<img width="1306" alt="70581623-b8854a00-1bf2-11ea-9720-2685376716a6 png (2692×1398) 2020-06-02 17-20-52" src="https://user-images.githubusercontent.com/21003054/83503369-8c89b800-a4f5-11ea-84f7-15a3255c8409.png">
