### ISSUE TITLE
(1) Not allowed to change Interest Amount after submission

### ISSUE THREAD

**Issue by dottenbr** [newmatik/dunning#32]
Trying to change from "unresolved" to "resolved"

https://staging.newmatik.com/desk#Form/Dunning/PR-DE-19-00004

![image](https://user-images.githubusercontent.com/9136094/70848168-cd214680-1e6d-11ea-8869-32d4f7694e44.png)

**Comment by KanchanChauhan** [comment]
@dottenbr The problem is arising because of the precision. The amounts are being saved as it is from JS. But when we change resolution type and update, as part of update validation from core it tries to fix the precision and hence the error since we cannot change the value after submit.

<img width="627" alt="Screen Shot 2019-12-16 at 11 58 16 AM" src="https://user-images.githubusercontent.com/16913064/70884288-9f6a0800-1ffb-11ea-9f6a-61467405767f.png">

Made a fix that amount should be saved based on currency precision in the first place.
https://github.com/newmatik/dunning/pull/35

**Comment by KanchanChauhan** [comment]
**STAGING TEST PASSED**

No error now

<img width="1089" alt="Screen Shot 2019-12-17 at 10 25 11 AM" src="https://user-images.githubusercontent.com/16913064/70965993-99396180-20b7-11ea-9c4a-360e4416b23c.png">
