### ISSUE TITLE
(1) Create Unit Test

### ISSUE THREAD

**Issue by dottenbr** [newmatik/dunning#8]
### Ratings:

Effort: **Low**
Complexity: **Low**
Unknown: **Low**

### Task

Create a basic unit test to make this contributable.

**Comment by KanchanChauhan** [comment]
@dottenbr I started creating unit test but they do not have a test setup like erpnext or frappe. So creating a simple test will be very time-consuming. Need to start from scratch and create test records:
1.  Create Company
2. Create Items
3. Create Item Group
4. Create Company Accounts
5. Create Customer
6. Create Sales Order
7. Create Sales Invoice
8. After all these requirements are satisfied, then we can create test for Dunning.

Even after this, I am afraid tests won't run since they do not have travis or any other setup.

**Comment by dottenbr** [comment]
Ok, let's put this on the back burner for now.
